// Configuration generated by Firebase Integration
export const firebaseConfig = {
  projectId: "ace-card-vxctm",
  appId: "1:701271040580:web:3fb20c20500c0a7afb9211",
  apiKey: "AIzaSyA2cCTo4BKy0TdBzWkcrpORxhgxJ_6K3GU",
  authDomain: "ace-card-vxctm.firebaseapp.com",
  firestoreDatabaseId: "ai-studio-portalconcursopa-df87bba9-5677-4b4e-8070-b9c9fc9689ad",
  storageBucket: "ace-card-vxctm.firebasestorage.app",
  messagingSenderId: "701271040580",
  measurementId: "",
  oAuthClientId: "701271040580-r37692jo6dg6btq6caf5cph6b6k8p5rs.apps.googleusercontent.com",
  recaptchaSiteKey: ""
};

export default firebaseConfig;
